### ISSUE TITLE
The result problem

### ISSUE THREAD

**Issue by 13331112522** [BCV-Uniandes/DMS#27]
I have tried to reproduce the code. The code ran smoothly but the result was far below the ones as you mentioned in the paper, I used the weights you provide and max mIoU was 0.11. When I visualize it, it's totally messy. I was wondering the reason.

**Comment by andfoy** [comment]
Hi,
Thanks for contacting us, this is a well-known issue: https://github.com/BCV-Uniandes/DMS/issues/21. Could you please try and follow the instructions posted there? That should fix the issue. If you keep experiencing problems, feel free to continue the discussion here.

**Comment by 13331112522** [comment]
@andfoy Great thanks for your timely reply. I followed the instruction to update the SRU to 2.1.3 which already support Prnvrtc 9.2. But my problem is still there.

python -u -m dmn_pytorch.train_gai --data referit_data --dataset referit --val val --backend dpn92 --num-filters 10 --lang-layers 3 --mix-we --save-folder weights --snapshot dmn_referit_weights.pth --epochs 0 --eval-first

Evaluation done. Elapsed time: 1035.489 (s)
Maximum IoU: 0.1528985351324 - Threshold: 0.0000000000000

I couldn't add --high-res because of out of memory problem, I had nvidia 2080 with 8G memory. I don't know the reason why it's so easy to leak.
Thanks for your consideration.

**Comment by 13331112522** [comment]
P.S: Dependency:
Python 3.6,8
Pytorch 1.0.1
CUDA 10
sru 2.1.3
prnvrtc 9.2
Window 10

**Comment by andfoy** [comment]
I'm closing this one in favour of #21
